# Generated by Django 3.2.9 on 2021-11-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friend_connectionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friendid',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='friend',
            name='connectionid',
            field=models.TextField(default=''),
        ),
    ]
