# Generated by Django 3.2.9 on 2021-11-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_auto_20211121_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
