# Generated by Django 3.2.9 on 2021-11-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='friend',
        ),
    ]
