# Generated by Django 3.2.9 on 2021-11-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_groupchat_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='groupid',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='groupname',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='connectionid',
            field=models.TextField(default=''),
        ),
    ]
