# Generated by Django 3.2.9 on 2021-11-20 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupmembers', '0002_alter_groupmembers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembers',
            name='groupid',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='groupname',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
